runtime: python37
service: flaskpy

includes:
    - var.yaml
# env_variables:
#     QUEUE_NAME: ""

instance_class: F1
automatic_scaling:
    min_instances: 0
    max_instances: 5


handlers:
    - url: /.*
      script: auto
